CREATE TABLE CUSTOMER
(
    CUSTOMER_ID number (38,0) NOT NULL,
    NAME varchar NOT NULL,
    ADDRESS varchar NOT NULL,
    LOCATION_ID number (38,0) NOT NULL,
    PHONE varchar NOT NULL,
    ACCOUNT_BALANCE number (12,2) NOT NULL,
    MARKET_SEGMENT varchar NOT NULL,
    COMMENT varchar,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY ( CUSTOMER_ID ),
    CONSTRAINT FK_CUSTOMER_BASED_IN_LOCATION FOREIGN KEY ( LOCATION_ID ) REFERENCES LOCATION ( LOCATION_ID )
)
COMMENT = 'Registered customers';
