--Set Variable
set department = 'DTS';


--Build rest of the variables based on value for department
set account_role_analyst = 'SF_WKSP_' || $DEPARTMENT || '_ANALYST'; --Read Only
set account_role_developer = 'SF_WKSP_' || $DEPARTMENT || '_DEVELOPER'; --ReadWrite
set account_role_owner = 'SF_WKSP_' || $DEPARTMENT || '_OWNER'; -- Ownership

set database = 'WKSP_' || $DEPARTMENT;
set warehouse = 'WKSP_' || $DEPARTMENT;

set database_read_role = 'DB_' || $DATABASE || '_R';
set database_readwrite_role = 'DB_' || $DATABASE || '_RW';
set database_full_role = 'DB_' || $DATABASE || '_FULL';

set warehouse_usage_role = 'WH_' || $WAREHOUSE || '_USAGE';
set warehouse_modify_role = 'WH_' || $WAREHOUSE || '_MODIFY';
set warehouse_full_role = 'WH_' || $WAREHOUSE || '_FULL';





--CREATE DATABASE, WAREHOUSE AND ACCOUNT ROLES
USE ROLE USERADMIN;

CREATE ROLE IDENTIFIER($DATABASE_READ_ROLE);
CREATE ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
CREATE ROLE IDENTIFIER($DATABASE_FULL_ROLE);

CREATE ROLE IDENTIFIER($WAREHOUSE_USAGE_ROLE);
CREATE ROLE IDENTIFIER($WAREHOUSE_MODIFY_ROLE);
CREATE ROLE IDENTIFIER($WAREHOUSE_FULL_ROLE);

CREATE ROLE IDENTIFIER($ACCOUNT_ROLE_ANALYST);
CREATE ROLE IDENTIFIER($ACCOUNT_ROLE_DEVELOPER);
CREATE ROLE IDENTIFIER($ACCOUNT_ROLE_OWNER);





--ASSIGN DATABASE ROLES TO ACCOUNT ROLES
--ASSIGN WAREHOUSE ROLES TO ACCOUNT ROLES
USE ROLE USERADMIN;
GRANT ROLE IDENTIFIER($DATABASE_READ_ROLE) TO ROLE IDENTIFIER($ACCOUNT_ROLE_ANALYST) ;
GRANT ROLE IDENTIFIER($DATABASE_READWRITE_ROLE) TO ROLE IDENTIFIER($ACCOUNT_ROLE_DEVELOPER) ; 
GRANT ROLE IDENTIFIER($DATABASE_FULL_ROLE) TO ROLE IDENTIFIER($ACCOUNT_ROLE_OWNER) ; 


GRANT ROLE IDENTIFIER($WAREHOUSE_USAGE_ROLE) TO ROLE IDENTIFIER($ACCOUNT_ROLE_ANALYST) ;
GRANT ROLE IDENTIFIER($WAREHOUSE_MODIFY_ROLE) TO ROLE IDENTIFIER($ACCOUNT_ROLE_DEVELOPER) ; 
GRANT ROLE IDENTIFIER($WAREHOUSE_FULL_ROLE) TO ROLE IDENTIFIER($ACCOUNT_ROLE_OWNER) ;







--Grant Privileges to WAREHOUSE Usage Role
USE ROLE SECURITYADMIN;
GRANT USAGE ON WAREHOUSE IDENTIFIER($WAREHOUSE) TO ROLE IDENTIFIER($WAREHOUSE_USAGE_ROLE);
GRANT USAGE, MONITOR,MODIFY ON WAREHOUSE IDENTIFIER($WAREHOUSE) TO ROLE IDENTIFIER($WAREHOUSE_MODIFY_ROLE);
GRANT OWNERSHIP ON WAREHOUSE IDENTIFIER($WAREHOUSE) TO ROLE IDENTIFIER($WAREHOUSE_FULL_ROLE);





--Grant Privileges to DATABASE READ ROLE
USE ROLE SECURITYADMIN;
GRANT USAGE ON DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READ_ROLE);
GRANT USAGE ON ALL SCHEMAS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READ_ROLE);

GRANT SELECT ON ALL TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READ_ROLE);
GRANT SELECT ON FUTURE TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READ_ROLE);
GRANT SELECT ON ALL VIEWS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READ_ROLE);
GRANT SELECT ON FUTURE VIEWS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READ_ROLE);
GRANT USAGE ON ALL SEQUENCES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READ_ROLE);
GRANT USAGE ON FUTURE SEQUENCES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READ_ROLE);
GRANT USAGE ON ALL STAGES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READ_ROLE);
GRANT READ ON ALL STAGES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READ_ROLE);
GRANT USAGE ON FUTURE STAGES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READ_ROLE);
GRANT READ ON FUTURE STAGES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READ_ROLE);
GRANT USAGE ON ALL FILE FORMATS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READ_ROLE);
GRANT USAGE ON FUTURE FILE FORMATS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READ_ROLE);
GRANT SELECT ON ALL STREAMS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READ_ROLE);
GRANT SELECT ON FUTURE STREAMS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READ_ROLE);
GRANT USAGE ON ALL PROCEDURES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READ_ROLE);
GRANT USAGE ON FUTURE PROCEDURES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READ_ROLE);
GRANT USAGE ON ALL FUNCTIONS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READ_ROLE);
GRANT USAGE ON FUTURE FUNCTIONS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READ_ROLE);
GRANT SELECT ON ALL MATERIALIZED VIEWS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READ_ROLE);
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READ_ROLE);
GRANT SELECT ON ALL DYNAMIC TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READ_ROLE);
GRANT SELECT ON FUTURE DYNAMIC TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READ_ROLE);




--Grant Privileges to DATABASE READ WRITE ROLE
USE ROLE SECURITYADMIN;
GRANT USAGE ON DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT USAGE ON ALL SCHEMAS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);

GRANT SELECT ON ALL TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT SELECT ON FUTURE TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT SELECT ON ALL VIEWS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT SELECT ON FUTURE VIEWS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT USAGE ON ALL SEQUENCES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT USAGE ON FUTURE SEQUENCES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT USAGE ON ALL STAGES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT READ ON ALL STAGES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT USAGE ON FUTURE STAGES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT READ ON FUTURE STAGES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT USAGE ON ALL FILE FORMATS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT USAGE ON FUTURE FILE FORMATS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT SELECT ON ALL STREAMS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT SELECT ON FUTURE STREAMS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT USAGE ON ALL PROCEDURES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT USAGE ON FUTURE PROCEDURES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT USAGE ON ALL FUNCTIONS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT USAGE ON FUTURE FUNCTIONS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT SELECT ON ALL MATERIALIZED VIEWS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT INSERT ON ALL TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT UPDATE ON ALL TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT DELETE ON ALL TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT REFERENCES ON ALL TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT INSERT ON FUTURE TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT UPDATE ON FUTURE TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT DELETE ON FUTURE TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT REFERENCES ON FUTURE TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT WRITE ON FUTURE STAGES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT WRITE ON ALL STAGES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT MONITOR ON ALL TASKS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT OPERATE ON ALL TASKS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT MONITOR ON FUTURE TASKS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT OPERATE ON FUTURE TASKS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT SELECT ON ALL DYNAMIC TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT SELECT ON FUTURE DYNAMIC TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT OPERATE ON ALL DYNAMIC TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);
GRANT OPERATE ON FUTURE DYNAMIC TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_READWRITE_ROLE);




--Grant Privileges to DATABASE FULL ACCESS ROLE
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS IDENTIFIER($DATABASE_FULL_ROLE);


USE ROLE SECURITYADMIN;
GRANT USAGE ON DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT USAGE ON ALL SCHEMAS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;

GRANT OWNERSHIP ON ALL TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)   COPY CURRENT GRANTS;
--GRANT OWNERSHIP ON FUTURE TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT OWNERSHIP ON ALL VIEWS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)   COPY CURRENT GRANTS;
--GRANT OWNERSHIP ON FUTURE VIEWS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT OWNERSHIP ON ALL SEQUENCES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)   COPY CURRENT GRANTS;
--GRANT OWNERSHIP ON FUTURE SEQUENCES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT OWNERSHIP ON ALL STAGES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)   COPY CURRENT GRANTS;
--GRANT OWNERSHIP ON FUTURE STAGES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT OWNERSHIP ON ALL FILE FORMATS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)   COPY CURRENT GRANTS;
--GRANT OWNERSHIP ON FUTURE FILE FORMATS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT OWNERSHIP ON ALL STREAMS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)   COPY CURRENT GRANTS;
--GRANT OWNERSHIP ON FUTURE STREAMS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT OWNERSHIP ON ALL PROCEDURES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)   COPY CURRENT GRANTS;
--GRANT OWNERSHIP ON FUTURE PROCEDURES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT OWNERSHIP ON ALL FUNCTIONS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)   COPY CURRENT GRANTS;
--GRANT OWNERSHIP ON FUTURE FUNCTIONS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT OWNERSHIP ON ALL MATERIALIZED VIEWS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)   COPY CURRENT GRANTS;
--GRANT OWNERSHIP ON FUTURE MATERIALIZED VIEWS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT OWNERSHIP ON ALL TASKS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)   COPY CURRENT GRANTS;
--GRANT OWNERSHIP ON FUTURE TASKS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT OWNERSHIP ON ALL DYNAMIC TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)   COPY CURRENT GRANTS;
--GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;

GRANT SELECT ON ALL TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT SELECT ON FUTURE TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT SELECT ON ALL VIEWS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT SELECT ON FUTURE VIEWS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT USAGE ON ALL SEQUENCES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT USAGE ON FUTURE SEQUENCES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT USAGE ON ALL STAGES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT READ ON ALL STAGES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT USAGE ON FUTURE STAGES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT READ ON FUTURE STAGES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT USAGE ON ALL FILE FORMATS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT USAGE ON FUTURE FILE FORMATS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT SELECT ON ALL STREAMS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT SELECT ON FUTURE STREAMS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT USAGE ON ALL PROCEDURES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT USAGE ON FUTURE PROCEDURES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT USAGE ON ALL FUNCTIONS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT USAGE ON FUTURE FUNCTIONS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT INSERT ON ALL TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT UPDATE ON ALL TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT DELETE ON ALL TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT REFERENCES ON ALL TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT INSERT ON FUTURE TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT UPDATE ON FUTURE TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT DELETE ON FUTURE TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT REFERENCES ON FUTURE TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT WRITE ON FUTURE STAGES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT WRITE ON ALL STAGES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT MONITOR ON ALL TASKS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT OPERATE ON ALL TASKS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT MONITOR ON FUTURE TASKS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT OPERATE ON FUTURE TASKS IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE)  ;
GRANT SELECT ON ALL DYNAMIC TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE);
GRANT SELECT ON FUTURE DYNAMIC TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE);
GRANT OPERATE ON ALL DYNAMIC TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE);
GRANT OPERATE ON FUTURE DYNAMIC TABLES IN DATABASE IDENTIFIER($DATABASE) TO ROLE IDENTIFIER($DATABASE_FULL_ROLE);


